### ISSUE TITLE
relative link test doesn't work as expected

### ISSUE THREAD

**Issue by doodzik** [gchallen/code.metalsmith-linkcheck#1]
If I link to a resource relatively the test fails even if the link works.

For example:
I'm on page `foo.xyz/bar/baz` and I want to link to `foo.xyz/bar/fizz`.
The link that we use looks like this: `./fizz`
I have this situation [here](https://github.com/doodzik/dudzik.co/edit/master/src/digress-into-minimalism/2016-08-01-moderation.md)

You can reproduce the behaviour by cloning [my website](https://github.com/doodzik/dudzik.co) and adding the link checker at the end of the pipeline.

**Comment by gchallen** [comment]
Thanks for the feedback. Closed by b9572f87359d879a740d80507335b9ba4be73f08.

**Comment by doodzik** [comment]
👍🏻👍🏻👍🏻
